CREATE TABLE IF NOT EXISTS WORDS(
	ID INTEGER			NOT NULL,
	WORD TEXT			NOT NULL,
	DESCRIPTION	TEXT	NOT NULL,
	PRIMARY KEY (ID)
);
CREATE SEQUENCE IF NOT EXISTS words_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1;

CREATE TABLE IF NOT EXISTS USERS(
	ID INTEGER			NOT NULL,
	USERNAME TEXT		NOT NULL,
	PASSWORD TEXT		NOT NULL,
	PRIMARY KEY (ID)
);
CREATE SEQUENCE IF NOT EXISTS users_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1;